### ISSUE TITLE
Improve exceptions handling in subscriptions follow-up payments process 

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#195]
Each subscription is associated with a gateway configuration. This gateway configuration can be deleted at any time. Once that happens, no follow-up payments can be started. In the process of starting the follow-up payments, we skip these subscriptions (`continue`). It is probably better to put these subscriptions on hold with a corresponding note.

https://github.com/pronamic/wp-pay-core/blob/3.0.1/src/Subscriptions/SubscriptionsModule.php#L1170-L1173

Furthermore, the creation and start-up of the follow-up payment may also fail. Also in this case it might be better to put the subscription on hold. Or should the process automatically retry the next day on certain exceptions?

https://github.com/pronamic/wp-pay-core/blob/3.0.1/src/Subscriptions/SubscriptionsModule.php#L1177-L1181

https://github.com/pronamic/wp-pay-core/blob/3.0.1/src/Subscriptions/SubscriptionsModule.php#L1187-L1191

**Comment by rvdsteege** [comment]
Setting subscriptions `On hold` if the gateway configuration does not exist anymore makes sense.

Error handling on start of recurring payments probably needs some additional thought/work. For example, starting the payment could fail because the gateway API is not available at that moment due to maintenance or an outage. In this case, we might want to try the payment again at a later time. If starting the payment fails because of invalid data along the way, putting the subscription `On hold` seems the right choice.

**Comment by rvdsteege** [comment]
> In the process of starting the follow-up payments, we skip these subscriptions (continue). It is probably better to put these subscriptions on hold with a corresponding note.

Subscriptions are put on hold with recent changes. I've added the note in https://github.com/pronamic/wp-pay-core/commit/7e32adb935f27fde47f7cae8ab56cbfc378bf858

> Or should the process automatically retry the next day on certain exceptions?

This has also already be updated to be handled downstream:
- https://github.com/pronamic/wp-pronamic-pay-mollie/blob/4.1.0/src/Gateway.php#L447-L491
