### ISSUE TITLE
Update for ING iDEAL 2.0

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#307]
ING is moving to a new platform:
- https://www.ing.nl/zakelijk/betalen/geld-ontvangen/idealupgrade/index.html
- [iDEAL Migration Manual Step by Step](https://github.com/pronamic/wp-pronamic-pay/files/8041900/iDEAL.Migration.Manual.Step.by.Step_tcm162-236314.pdf) (PDF)

iDEAL Basic will no longer be available and for iDEAL Advanced, the integration needs to be updated:

> In order to process iDEAL transactions via the new platform, three modifications will have to be made to the configuration of your iDEAL integration.
>
> 1. Merchant ID
> 2. Acquiring URL
> 3. ING signing certificate
>
> Apart from these three configuration modifications, there are no other functional changes.

## Merchant ID
These will all need to be updated:
> […] the first four digits will change from 0050 to 0051. For example, if your old merchant ID is 005012345, your new merchant ID will be 005112345.

#### Production
- Generic (accepts all messages): https://ideal-acquiring.ing.nl/ideal/iDEALv3

If you have configured separate URLs for the three types of messages:
1. Directory Request → https://ideal-acquiring.ing.nl/ideal/iDEALv3/directory
2. Transaction Request → https://ideal-acquiring.ing.nl/ideal/iDEALv3/transaction
3. Status Request → https://ideal-acquiring.ing.nl/ideal/iDEALv3/status

#### Sandbox
- Generic (accepts all messages): https://sandbox.ideal-acquiring.ing.nl/ideal/iDEALv3

If you have configured separate URLs for the three types of messages:
1. Directory Request → https://sandbox.ideal-acquiring.ing.nl/ideal/iDEALv3/directory
2. Transaction Request → https://sandbox.ideal-acquiring.ing.nl/ideal/iDEALv3/transaction
3. Status Request → https://sandbox.ideal-acquiring.ing.nl/ideal/iDEALv3/status

**Comment by remcotolsma** [comment]
Some work in progress in: https://github.com/pronamic/wp-pronamic-pay/commit/e56f4de590ed7b78748696710ff264acc23ca7c5 and https://github.com/pronamic/wp-pronamic-pay/commit/e99139e128f25c4922dc15546f2eedcab7f952dd.

I want to remove the test and live mode setting and add two separate gateways, one for production and one for the sandbox:

- ING - iDEAL Advanced - New platform - Production
- ING - iDEAL Advanced - New platform - Sandbox

Because the production and sandbox environment have their own dashboard URL, payment server URL and signing certificates.

With this we can also simplify the code further.

**Comment by remcotolsma** [comment]
> I want to remove the test and live mode setting and add two separate gateways, one for production and one for the sandbox:
> 
> * ING - iDEAL Advanced - New platform - Production
> * ING - iDEAL Advanced - New platform - Sandbox
> 
> Because the production and sandbox environment have their own dashboard URL, payment server URL and signing certificates.

I have opened the following issues for this:

- https://github.com/pronamic/wp-pronamic-pay/issues/308
